### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by loriab** [piecuch-group/cct3#1]
I had heard of this plugin, but it took a while to find it. We'd like to mention this in the upcoming Psi4 paper. A few questions:
* ok with you to mention and cite the plugin?
* are these the best citations?
<img width="738" alt="Screen Shot 2020-02-11 at 11 39 31 AM" src="https://user-images.githubusercontent.com/2314730/74259327-b9eff300-4cc5-11ea-86e0-6b7e6ef6e58a.png">

* brief summary of "active-space, method-of-moments CC" ok?
* I haven't yet tried to compile and run the plugin. Assuming no major roadblocks, would you be willing for it to be packaged for conda and installable alongside psi4 with `conda install cct3 -c psi4`?
* any comments on ease-of-use or things to improve psi4-side?

Thanks!

**Comment by edeustua** [comment]
Hi Lori!

I think all your questions were solved in Prof. Piecuch's email. Let me know if you need anything else.

Best.
